name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Build the iOS app
      - name: Build iOS .ipa
        run: flutter build ios --release --no-codesign

      # Upload the build artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/ipa/
